FROM golang:1.17-alpine as build
RUN apk add --update --no-cache make \
  && rm -rf /var/cache/apk/*

RUN go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.9.0
RUN go install github.com/golang/mock/mockgen@v1.6.0
